version: '3'
services:
  frontend:
    image: musicx-web:latest
    ports:
      - 2222:80
    networks:
      - mynetwork
  backend:
    image: musicx-server:latest
    ports:
      - 35530:35530
    networks:
      - mynetwork
networks:
  mynetwork: